# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project info
site_name: C*Base Reference Guide
site_description: Reference guide and collection of all things related to C*Base for the Commodore 64
site_author: C*Base Reference Guide Team
site_url: https://cbasereferenceguide.github.io

# Local build
#site_url: ""
#use_directory_urls: false

# Repository
repo_name: 'cbasereferenceguide.github.io'
repo_url: 'https://github.com/cbasereferenceguide/cbasereferenceguide.github.io'

# Copyright
copyright: >
  C*Base Reference Guide, 2024-2025 –
  <a href="#__consent">Manage cookies</a>

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    # - navigation.expand
    #- navigation.prune
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  font:
    text: Noto Sans
    code: Roboto Mono
  favicon: assets/favicon/favicon.png
  icon:
    logo: simple/commodore

# Plugins
plugins:
  - mkdocs-video:
  - privacy:
      assets: false
  - tags:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  #- minify:
  #    minify_html: true
  # - offline:
  #    enabled: true

# Additional configuration
extra:
  homepage: https://cbasereferenceguide.github.io
  analytics:
    provider: google
    property: G-R0H2BDF9CX
  consent:
    title: How about some cookies?
    description: 
      Cookies help us improve functionality, remember your preferences, and analyze usage to ensure the best possible experience. You can choose to accept all cookies or customize your preferences. By continuing to use this guide, you agree to our use of cookies.
    actions:
      - accept
      - reject
      - manage

extra_css:
  #- assets/css/custom.css
  - assets/css/test.css

extra_javascript:
  - assets/js/typewriter.js
  - https://unpkg.com/typeit@8.7.1/dist/index.umd.js

# Extensions
markdown_extensions:
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      toc_depth: 3
      permalink: true
      title: On this page
      permalink_title: Anchor link to this section for reference
  - admonition
  - footnotes

  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.details
  - tables
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - Resources:
    - resources/index.md
    - C*Base:
      - For Commodore 64/128: resources/cbase/for-commodore64-128.md
      - For Ultimate64: resources/cbase/for-ultimate64.md
      - Manuals: resources/cbase/manuals.md
      - Prompt editors: resources/cbase/prompt-editors.md
      - Sources: resources/cbase/sources.md
    - C*Base Games:
        - Alien Attack: resources/cbase-games/alien-attack.md
        - Dragonslayer: resources/cbase-games/dragonslayer.md
        - Eliza: resources/cbase-games/eliza.md
        - Forest Fire: resources/cbase-games/forest-fire.md
        - Goldmine: resources/cbase-games/goldmine.md
        - LIFE: resources/cbase-games/life.md
        - Oceangunner: resources/cbase-games/oceangunner.md
        - Puzzler: resources/cbase-games/puzzler.md
    - Hardware:
      - Commodore: resources/hardware/commodore.md
      - Creative Micro Designs: resources/hardware/creative-micro-designs.md
      - Turbo Chameleon: resources/hardware/turbo-chameleon.md
      - Xetec Lt. Kernal: resources/hardware/xetec-lt-kernal.md
    - Hardware enhancements:
      - JiffyDOS: resources/hardware-enhancements/jiffydos.md
  - PETSCII:
    - PETSCII: petscii/index.md
    - History: petscii/history.md
    - Character set: petscii/character-set.md
    - Creative platform: petscii/creative-platform.md
    - Converters: petscii/converters.md
    - Editors: petscii/editors.md
    - Tools: petscii/tools.md
    - Viewers: petscii/viewers.md
  - About:
    - About: about/index.md
    - Changelog: about/changelog.md
    - Contributors:
      - Jucke/Judas: about/contributors/jucke-judas.md
      - Larry/ROLE: about/contributors/larry-role.md
      - Skyhawk/Triad: about/contributors/skyhawk-triad.md
      - Tao/Triad: about/contributors/tao-triad.md
      - Taper/Triad: about/contributors/taper-triad.md
    - Legal:
      - GNU General Public License: about/legal/license.md
      - Copyrights and trademarks: about/legal/copyrights-trademarks.md
