# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project info
site_name: C*Base Reference Guide
site_description: Reference guide and collection of all things related to C*Base for the Commodore 64
site_author: C*Base Reference Guide Team
site_url: https://cbasereferenceguide.github.io

# Local build
#site_url: ""
#use_directory_urls: false

# Repository
repo_name: 'cbasereferenceguide.github.io'
repo_url: 'https://github.com/cbasereferenceguide/cbasereferenceguide.github.io'

# Copyright
copyright: C*Base Reference Guide, 2024-2025

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    # - navigation.expand
    #- navigation.prune
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  font:
    text: Noto Sans
    code: Roboto Mono
  favicon: assets/favicon/favicon.png
  icon:
    logo: simple/commodore

# Plugins
plugins:
  - tags:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  #- minify:
  #    minify_html: true
  # - offline:
  #    enabled: true

# Additional configuration
extra:
  homepage: https://cbasereferenceguide.github.io

extra_css:
  #- assets/css/custom.css
  - assets/css/test.css

extra_javascript:
  - assets/js/typewriter.js
  - https://unpkg.com/typeit@8.7.1/dist/index.umd.js

# Extensions
markdown_extensions:
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      toc_depth: 3
      permalink: true
      title: On this page
      permalink_title: Anchor link to this section for reference
  - admonition
  - footnotes
  - pymdownx.keys
  - pymdownx.details
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - Resources:
    - Resources: resources/index.md
    - C*Base:
      - For Commodore 64/128: resources/cbase/for-commodore64-128.md
      - For Ultimate64: resources/cbase/for-ultimate64.md
      - Manuals: resources/cbase/manuals.md
      - Sources: resources/cbase/sources.md
  - About:
    - About: about/index.md
    - Changelog: about/changelog.md
    - Contributors: about/contributors.md
    - Legal:
      - GNU General Public License: about/legal/license.md
      - Trademarks: about/legal/trademarks.md      